### ISSUE TITLE
Add a Back Button in ProfileScreen

### ISSUE THREAD

**Issue by SanjaySargam** [SanjaySargam/opencollectiveandroid#4]
![WhatsApp Image 2023-10-02 at 6 58 01 PM](https://github.com/SanjaySargam/opencollectiveandroid/assets/65113071/2c27081c-5a73-46cb-926a-6f69599e317b)

**Comment by Durgeshsejekar** [comment]
I want to work on this issue can you assign me.

**Comment by shlok-2003** [comment]
Hey @SanjaySargam, I am interested in this issue. Can you please assign it to me
